base/urls.py
from django.contrib import admin
from django.urls import path, include

from base.views import principal, logout_user
# para las iamgenes
from django.conf import settings
from django.conf.urls.static import static
# para la gestion de login y contraseña
from django.contrib.auth import views as auth_views
urlpatterns = [
    #gestion de login y contraseña
    path('',auth_views.LoginView.as_view(),name='inicio'),
    path('reiniciar/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('reiniciar/enviar',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reiniciar/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reiniciar/completo',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('logout/',logout_user,name="logout"),
    
    path('admin/', admin.site.urls),
    path('inicio/', principal, name="index" ),
    path('usuarios/', include('usuarios.urls') ),
    path('productos/', include('productos.urls')),
    path('ventas/', include('ventas.urls')),
    path('compras/', include('compras.urls')),
   


    

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from usuarios.views import usuario_listar, usuario_crear, usuario_modificar, usuario_eliminar

urlpatterns = [
    path('usuario/<int:visualizar>/', usuario_listar, name="usuarios" ),
    path('usuario/', usuario_listar, name="usuarios" ),

    path('usuario/crear/', usuario_crear, name="usuarios-crear" ),
    path('usuario/modificar/<int:pk>/', usuario_modificar, name="usuarios-modificar" ),
    path('usuario/eliminar/<int:pk>/', usuario_eliminar, name="usuarios-eliminar" ),
    

]

usuarios/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.

class Usuario(models.Model):
    nombre= models.CharField(max_length=45,verbose_name="Nombres",default="Nombres")
    apellido= models.CharField(max_length=45,verbose_name="Apellidos", default="Apellidos") 
    class TipoDocumento(models.TextChoices):
        CEDULA='CC',_("Cédula")
        NIT='NIT',_("NIT")
        CEDULA_EXTRANJERIA='CE',_("Cédula de Extranjería")
    tipo_documento=models.CharField(max_length=20,choices=TipoDocumento.choices,verbose_name="Tipo de Documento")
    documento= models.PositiveIntegerField(verbose_name="Documento", unique=True)
    class RH(models.TextChoices):
        OP='OP',_("O+")
        ON='ON',_("O-")
        AP='AP',_("A+")
        AN='AN',_("A-")
        BP='BP',_("B+")
        BN='BN',_("B-")
        ABP='ABP',_("AB+")
        ABN='ABN',_("AB-")
        
    rh= models.CharField(max_length=3,choices=RH.choices,verbose_name="Factor RH")
    class TipoUsuario(models.TextChoices):
        ADMINISTRADOR='A',_("Administrador")
        SECRETARIA='S',_("Secretaria")    
    tipoUsuario=models.CharField(max_length=2,choices=TipoUsuario.choices,verbose_name="tipoUsuario", default="Administrador")
    correo= models.EmailField(max_length=50, verbose_name="Correo",default="lubricentro@gmail.com")
    telefono=models.PositiveIntegerField(verbose_name="Teléfono",default="3149675543")
    direccion=models.CharField(max_length=15,verbose_name="Dirección", default="cra3 #4-5")
    class Estado(models.TextChoices):
        ACTIVO='1',_("Activo")
        INACTIVO='0',_("Inactivo")
    estado=models.CharField(max_length=1,choices=Estado.choices,default=Estado.ACTIVO,verbose_name="Estado")
   
        
    def clean(self):
        self.nombre= self.nombre.title() 
        self.apellido= self.apellido.title()
        self.correo= self.correo.lower()
        
                
    def __str__(self):
        return "%s %s"%(self.nombre,self.apellido)
    
    class Meta:
        verbose_name_plural = "Usuarios"

usuarios/forms.py
from django.core.files.uploadedfile import UploadedFile
from django.forms import ModelForm, widgets
from usuarios.models import Usuario
class UsuarioForm(ModelForm):
    
    class Meta:
        model = Usuario
        fields = "__all__"
        exclude=["estado",]
        
        
    def clean(self):
        cleaned_data = super().clean()
        documento = cleaned_data.get('documento')
        telefono= cleaned_data.get('telefono')
        
    

        if documento and len(str(documento)) > 12:
            self.add_error('documento', "El documento no puede tener más de 12 dígitos")

        if telefono and len(str(telefono)) > 10:
            self.add_error('telefono_contacto', "El teléfono no puede tener más de 10 dígitos")

    
        return cleaned_data
    
    def __init__(self, *args, **kwargs):
        super(UsuarioForm, self).__init__(*args, **kwargs)
        

class UsuarioUpdateForm(ModelForm):
    
    class Meta:
        model = Usuario
        fields = "__all__"
        exclude=["documento","rh"]
        

base/views.py
from django.shortcuts import redirect, render
from usuarios.models import Usuario
from productos.models import Producto
from ventas.models import Venta
from compras.models import Compra
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
@login_required
def principal(request):
    titulo="Bienvenido al Sistema"
    usuarios= Usuario.objects.all().count()
    productos=Producto.objects.all().count()
    ventas=Venta.objects.all().count()
    compras=Compra.objects.all().count()
   
    

    context={
        
        "usuarios":usuarios,
        "productos":productos,
        "ventas":ventas,
        "compras":compras,
        "titulo":titulo,
        
    }
    return render(request, "index.html",context)

def logout_user(request):
    logout(request)
    return redirect('inicio')

usuarios/views.py
from django.shortcuts import render, redirect, get_object_or_404
from usuarios.models import Usuario
from usuarios.forms import UsuarioForm,UsuarioUpdateForm

from django.contrib import messages
from django.urls import reverse, resolve
from django.urls import reverse
from . import urls
from django.core.paginator import Paginator, PageNotAnInteger
from django.contrib.auth.decorators import login_required

@login_required
def usuario_crear(request):
    titulo="Usuario"
    
    if request.method== 'POST':
        form= UsuarioForm(request.POST,request.FILES)
        if form.is_valid():
            usuario = form.save()
  
            usuario.save()
            messages.success(request, 'El usuario se ha creado correctamente.')

            return redirect('usuarios')
        else:
            messages.error(request, 'Los datos del usuario tienen errores.')
    else:
        form= UsuarioForm()
    context={
        "titulo":titulo,
        "form":form
        }
    return render(request,"usuarios/usuarios/crear.html", context)

@login_required
def usuario_listar(request, visualizar=1):
    titulo="Usuario"
    modulo="Usuarios"
    
    
    if visualizar==1:
        usuarios= Usuario.objects.filter(estado=visualizar)
    else:
        usuarios= Usuario.objects.all()

    paginator = Paginator(usuarios, 3) # 3 usuarios por página
    page_number = request.GET.get('page') # número de página actual
    try:
        usuarios = paginator.page(page_number)
    except PageNotAnInteger:
        # Si el número de página no es un entero, mostrar la primera página.
        usuarios = paginator.page(1)
    except EmptyPage:
        # Si el número de página está fuera de rango, mostrar la última página.
        usuarios = paginator.page(paginator.num_pages)
    context={
       

        "titulo":titulo,
        "modulo":modulo,
        "usuarios":usuarios,
        "visualizar":visualizar
    }
    return render(request,"usuarios/usuarios/listar.html", context)

@login_required
def usuario_modificar(request,pk):
    titulo="Usuario"
    usuario= Usuario.objects.get(id=pk)
    
    if request.method== 'POST':
        form= UsuarioUpdateForm(request.POST, instance=usuario)
        if form.is_valid():
            form.save()
            messages.success(request, 'El formulario se ha enviado correctamente.')
            return redirect('usuarios')
    else:
        form= UsuarioUpdateForm(instance=usuario)
    context={
        "titulo":titulo,
        "form":form
        }
    return render(request,"usuarios/usuarios/modificar.html", context)


def usuario_eliminar(request,pk):
    usuario= Usuario.objects.filter(id=pk)
    
    usuario.update(
        estado="0"
    )
    return redirect('usuarios')
   

base/templates/usuarios/usuarios/crear.html
{% extends 'partials/body.html' %}
{% load crispy_forms_tags %}


{% block contenido %}
<div class="container-fluid m-5">
<div class="rounded card p-3 col-md-4">
    <form method="POST"  enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <input class="btn btn-primary" type="submit" value="Agregar {{titulo}}">
    </form>
</div>
</div>
{% endblock contenido %}
    

base/templates/usuarios/usuarios/listar.html
{% extends 'partials/body.html' %}

{% block contenido %}

<div class="container-fluid m-5">
<a href="{% url 'usuarios-crear' %}" class="btn btn-success w-25">Crear {{titulo}}</a>

{% if visualizar == 1 %}
<a href="{% url 'usuarios' 0 %}" class="btn btn-success w-25">
{% else %}
<a href="{% url 'usuarios' 1 %}" class="btn btn-success w-25">
{% endif %}
{% if visualizar == 1 %}
Mostrar {{titulo}} Inactivos 
{% else %}
Ocultar {{titulo}} Inactivos
{% endif %}
</a>

</div>
<div class="container-fluid mb-5">
<table id="lista-tabla" class="table table-hover ">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Tipo de Documento</th>
            <th>Documento</th>
            <th>Rh</th>
            <th>Tipo Usuario</th>
            <th>Correo</th>
            <th>Teléfono</th>
            <th>Dirección</th>
            <th>Acciones</th>

        </tr>
    </thead>
    <tbody>
        
        {% for usuarios in usuario %}
        <tr
        {% if usuario.estado != "1" %}
         class="bg-warning"
        {% endif %}
        > 
        
        
            
            
                <td>{{usuario.nombre}}</td>
                <td>{{usuario.apellido}}</td>
                <td>{{usuario.get_tipo_documento_display}}</td>
                <td>{{usuario.documento}}</td>
                <td>{{usuario.get_rh_display}}</td>
                <td>{{usuario.get_tipoUsuario_display}}</td>
                <td>{{usuario.correo}}</td>
                <td>{{usuario.telefono}}</td>
                <td>{{usuario.direccion}}</td>
                
                    <button  type="button" data-indet="{{usuario.id}}" class="btnEliminar btn btn-danger"
                    data-bs-toggle="modal" data-bs-target="#modalConf">
                    <i class="bi bi-trash"></i>

                </button>
                    <a class="btn btn-primary" href="{% url 'usuarios-modificar' usuario.id %}"><i class="bi bi-pencil-square"></i></a>
                </td>

            </tr>
        {% endfor %}
            
    </tbody>
  </table>
</div>
<div class="container-fluid p-5">
 
  <nav class="pt-5">
    <ul class="pagination">
      {% if usuarios.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ usuarios.previous_page_number }}" tabindex="-1">Anterior</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Anterior</a>
      </li>
      {% endif %}
      {% for num in usuarios.paginator.page_range %}
        {% if usuarios.number == num %}
        <li class="page-item active" aria-current="page">
          <a class="page-link" href="#">{{ num }}</a>
        </li>
        {% else %}
        {% if num > usuarios.number|add:'-2' and num < usuarios.number|add:'1' %}
        <li class="page-item">
          <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}
        {% endif %}
      {% endfor %}
      {% if usuarios.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ usuarios.next_page_number }}">Siguiente</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" aria-disabled="true">Siguiente</a>
      </li>
      {% endif %}
    </ul>
  </nav>
</div>



  
{% endblock contenido %}
    

base/templates/usuarios/usuarios/modificar.html
{% extends 'partials/body.html' %}
{% load crispy_forms_tags %}


{% block contenido %}

        <form action="" method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <input class="btn btn-primary" type="submit" value="Modificar {{titulo}}">
        </form>
 
{% endblock contenido %}